[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCEbYhDd6c6vngsF5PQpFVWg"
title = "Tsoding"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCrqM0Ym_NbK1fqeQG2VIohg"
title = "Tsoding Daily"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCMlGfpWw-RUdWX_JbLCukXg"
title = "CppCon"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCJhay24LTpO1s4bIZxuIqKw"
title = "ACCU Conference"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCAczr0j6ZuiVaiGFZ4qxApw"
title = "cpponsea"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCxHAlbZQNFU2LgEtiqd2Maw"
title = "C++ Weekly With Jason Turner"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UC5e__RG9K3cHrPotPABnrwg"
title = "CppNow"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UC1kBxkk2bcG78YBX7LMl9pQ"
title = "code_report"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCkgKbO073CuS1ZZFKoOgTVw"
title = "Eyesomorphic"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCNi5dKk8OwjJrj8nWPf8aIg"
title = "Let's Chat with Stephen"

[[sources]]
type = "youtube"
url = "https://www.youtube.com/channel/UCQ-W1KE9EYfdxhL6S4twUNw"
title = "The Cherno"
